Imports TorneoEntidades
Module PartidoTest
    Sub main()
        Dim partidein As New Partido
        partidein.Fecha = #06/25/2015#
        Console.WriteLine("Fecha: {0}", partidein.Fecha)
        Console.WriteLine("Goles local: {0}", partidein.GolesLocal)
        Console.WriteLine("Goles visitante: {0}", partidein.GolesVisitante)
        Console.WriteLine()
        partidein.nuevoGolLocal(2)
        Console.WriteLine("Goles local: {0}", partidein.GolesLocal)
        Console.WriteLine("Goles visitante: {0}", partidein.GolesVisitante)
        'Console.WriteLine("minutos Goles local: {0}", partidein.MinutosGolesLocal)
        'Console.WriteLine("minutos Goles visitante: {0}", partidein.MinutosGolesVisitante)
        Console.WriteLine()
        partidein.nuevoGolLocal(3)
        partidein.nuevoGolVisitante(5)
        Console.WriteLine("Goles local: {0}", partidein.GolesLocal)
        Console.WriteLine("Goles visitante: {0}", partidein.GolesVisitante)
        'Console.WriteLine("minutos Goles local: {0}", partidein.MinutosGolesLocal)
        'Console.WriteLine("minutos Goles visitante: {0}", partidein.MinutosGolesVisitante)
        Console.WriteLine()
        partidein.nuevoGolVisitante(15)
        Console.WriteLine("Goles local: {0}", partidein.GolesLocal)
        Console.WriteLine("Goles visitante: {0}", partidein.GolesVisitante)
        'Console.WriteLine("minutos Goles local: {0}", partidein.MinutosGolesLocal)
        'Console.WriteLine("minutos Goles visitante: {0}", partidein.MinutosGolesVisitante)
        Console.WriteLine()
        partidein.nuevoGolVisitante(47)
        partidein.nuevoGolLocal(73)
        partidein.nuevoGolVisitante(74)
        partidein.nuevoGolVisitante(75)
        partidein.nuevoGolVisitante(85)
        Console.WriteLine("Goles local: {0}", partidein.GolesLocal)
        Console.WriteLine("Goles visitante: {0}", partidein.GolesVisitante)
        'Console.WriteLine("minutos Goles local: {0}", partidein.MinutosGolesLocal)
        'Console.WriteLine("minutos Goles visitante: {0}", partidein.MinutosGolesVisitante)
        Console.WriteLine()
        partidein.Finalizado()
        partidein.nuevoGolLocal(1)
        partidein.nuevoGolLocal(2)
        partidein.nuevoGolLocal(3)
        partidein.nuevoGolLocal(4)
        partidein.nuevoGolLocal(5)
        partidein.nuevoGolLocal(6)
        partidein.nuevoGolLocal(8)
        partidein.nuevoGolLocal(68)
        partidein.nuevoGolLocal(95)
        partidein.nuevoGolLocal(94)
        Console.WriteLine("Goles local: {0}", partidein.GolesLocal)
        Console.WriteLine("Goles visitante: {0}", partidein.GolesVisitante)
        'Console.WriteLine("minutos Goles local: {0}", partidein.MinutosGolesLocal)
        'Console.WriteLine("minutos Goles visitante: {0}", partidein.MinutosGolesVisitante)
        Console.WriteLine()
        For Each elemento In partidein.MinutosGolesLocal
            Console.WriteLine("minutos Goles local: {0}", elemento)
        Next
        Console.WriteLine()
        For Each elemento In partidein.MinutosGolesVisitante
            Console.WriteLine("minutos Goles visitante: {0}", elemento)
        Next
        Console.ReadKey()
    End Sub
End Module
